export const DEFAULT = 'LISTING_DEFAULT'

export const ADD_CONFIRMATION_PENDING = 'LISTING_ADD_PENDING'
export const ADD_FAILURE = 'LISTING_ADD_FAILURE'
export const DELETE_PENDING = 'LISTING_DELETE_PENDING'
export const DELETE_FAILURE = 'LISTING_DELETE_FAILURE'
export const EDIT_PENDING = 'LISTING_EDIT_PENDING'
export const EDIT_FAILURE = 'LISTING_EDIT_FAILURE'
